#ifndef PATTERN_H
#define PATTERN_H

#define A ".-"
#define B ".---"
#define C "-.-."
#define D "-.."
#define E "."
#define F "..-."
#define G "--."
#define H "...."
#define I ".."
#define J ".---"
#define K "-.-"
#define L ".-.."
#define M "--"
#define N "-."
#define O "---"
#define P ".--."
#define Q "--.-"
#define R ".-."
#define S "..."
#define T "-"
#define U "..-"
#define V "...-"
#define W ".--"
#define X "-..-"
#define Y "-.--"
#define Z "--.."
#define R0 "-----"
#define R1 ".----"
#define R2 "..---"
#define R3 "...--"
#define R4 "....-"
#define R5 "....."
#define R6 "-...."
#define R7 "--..."
#define R8 "---.."
#define R9 "----."
#define AMPER ".-..."
#define APOS ".----."
#define AT ".--.-."
#define CBRACKET "-.--.-"
#define OBRACKET "-.--."
#define COLON "---..."  
#define COMMA "--..--"
#define EQ "-...-"
#define EXCLAMATION "-.-.--"
#define FULLS ".-.-.-"
#define HYPEN "-....-"
#define PLUS ".-.-."
#define QUOT ".-..-."
#define QUEST "..--.."
#define SLASH "-..-."

#ifndef _WIN32
    #define PLAY1 "play -nq -V0 synth 0.1 sine 550"
    #define PLAY3 "play -nq -V0 synth 0.3 sine 550"
#else
#endif

#endif